### PR TITLE
use prediction get methods in partialPrediction functions

### PR DESCRIPTION
**Pull request by zmjones**
uses 3bfd3faa9ec4687747979faa66aac6d8bc2c4ef

some small adjustments since `getPredictionProbabilities` only returns the positive class for binary classification, which I pulled out in `generatePartialPredictionData` before.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Could you add a unit test for the different cases you handle in the change please?

**Comment by zmjones** [comment]
I am not sure what you mean. There are already tests for binary and multiclass classification and regression in the tests for this, so if any of these changes broke that then they would fail.

**Comment by larskotthoff** [comment]
Ok, I'm probably misunderstanding what you did here -- is this only a cleanup commit, i.e. the behaviour of the function for different numbers of classes hasn't changed?

**Comment by zmjones** [comment]
Correct, this is just using the helper "get" functions just added for `Prediction` objects, instead of pulling things out manually, and this resulted in me having to modify the internal behavior slightly.

**Comment by larskotthoff** [comment]
Ok, thanks for the clarification. Merging.

**Pull request merged**
