### PR TITLE
introduced budget parameter to tuning

### PR DESCRIPTION
**Pull request by kerschke**
once again adding the budget parameter

### CODE REVIEW

**Comment by kerschke** [comment]
I just tried to stay consistent with the rest of the code.. And as you can see, you guys already used `convertToShortString` within the same function.
Or am I misinterpreting it?

**Comment by berndbischl** [comment]
Yes, that functon is for complex objects like lists and so on.

**Comment by berndbischl** [comment]
You just have an integer.

**Comment by berndbischl** [comment]
Do you have unit tests that try to check whether the budget is properly respected?

**Comment by berndbischl** [comment]
I just merged and will iterate a bit

**Comment by berndbischl** [comment]
If you read this go on hangout so we can review 10 min?

**Pull request merged**
