### PR TITLE
update tutorial with plot/generate and ggvis

### PR DESCRIPTION
**Pull request by zmjones**

### CODE REVIEW

**Comment by berndbischl** [comment]
@schiffner 
Do you wanna check this?

**Comment by schiffner** [comment]
Thank you very much.

I have done a little proofreading and spotted some mix-ups between & and % in links here: 
feature_selection.Rmd: l. 50, 52
learning_curve.Rmd: l. 40, 68, 70
performance.Rmd: 149, 150  
Also there is a typo in performance.Rmd, l. 128 (is are)

**Comment by zmjones** [comment]
ah woops. thanks for checking. fixing it now.

**Comment by schiffner** [comment]
Thanks. I will merge.

**Pull request merged**
