### PR TITLE
Final commit for #247

### PR DESCRIPTION
**Pull request by luizfox**
It looks like my NAMESPACE file is a bit difference after I did run roxygen, but related with 
S3method(makeRLearner,classif.sparseLDA)
which I haven't changed. 

I'm sending the commit anyway

### CODE REVIEW

**Comment by larskotthoff** [comment]
It looks like it still fails with the same error from the kohonen package, which should be fixed in master. Did you rebase before making your changes?

**Comment by luizfox** [comment]
Yes, it says my `current branch master is up to date.`

**Comment by larskotthoff** [comment]
Ok, when you run the tests locally, do you get the same error? Do you also get it in the master branch?

**Comment by luizfox** [comment]
No, it stops before it: 

Running the tests in 'tests/run-base.R' failed.
Last 13 lines of output:
  makeRegrTask(data = multiclass.df, target = multiclass.target) does not match
''numeric''. Actual value: "Error in test_check("mlr", filter = "base") : \n  As
sertion on 'Species' failed: Must be numeric\n"

  4. Failure(@test_base_UnsupervisedTask.R#6): UnsupervisedTask ----------------
--
  makeClassifTask(data = 44) does not match ''data.frame''. Actual value: "Error
 in test_check("mlr", filter = "base") : \n  Assertion on 'data' failed: Must be
 a data frame\n"

**Comment by larskotthoff** [comment]
Hmm, probably an out of date package. I'll have a more detailed look at this tomorrow, but could you try to make the tests pass on your machine as they do in travis please?

**Comment by luizfox** [comment]
Right, I'll do it.

**Comment by larskotthoff** [comment]
Ok, I've rerun the build for master and that's broken as well now with the same error as yours. This is something we'll need to fix in the master branch, so don't worry about it here -- your pull request looks fine.

**Comment by luizfox** [comment]
Thanks,  Lars. I feel relieved :)

**Comment by larskotthoff** [comment]
Luiz, this has been fixed by another commit. Thanks for your work on this though, it's much appreciated.

**Comment by luizfox** [comment]
Cool, Lars. Thanks and sorry for any mistake :)

**Pull request closed without merging**
