### PR TITLE
adds generic permutation.importance filter

### PR DESCRIPTION
**Pull request by zmjones**
- user specified aggregation, contrast, measure, and learner

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Could you document it as well please?

**Comment by zmjones** [comment]
where should I document it?

**Comment by larskotthoff** [comment]
Ah, good point -- I thought that the other ones were documented in the source file. This is probably something that should go in the tutorial (my main point here is that it's not entirely obvious what `contrast` should be and an example and some explanation would help). I'll merge this for now.

**Comment by zmjones** [comment]
Yea no that occurred to me too. Maybe we could add some more information to the filter objects?

**Comment by larskotthoff** [comment]
Yep, sounds good. It might even be worth making this a separate section of the tutorial and then only referencing it in the feature selection section. @berndbischl @schiffner

**Comment by zmjones** [comment]
Yea that makes sense. 

It occurred to me also, just now, that `generateFilterValuesData`, which can take a vector of filter methods, might be a little weird with this filter. Shouldn't it be possible to calculate and compare permutation importance using many different learners and/or measures, contrast functions, aggregation functions, etc.?  Maybe this could be made more general by writing a `generatePermutationImportanceData` function which is not set up to only support feature selection. 

However this is maybe a bit messy. Thoughts?

**Comment by larskotthoff** [comment]
That makes sense, but you could get that by simply having a loop around the filter function, calling it with different arguments every time. Unless I'm missing something this doesn't warrant a new function for me.

**Comment by zmjones** [comment]
Now that I think about it more this is consistent with the others in that you can pass different parameters to other functions and get different output. This just *seemed* different because the user specifies more or less the whole thing.

**Comment by zmjones** [comment]
It would be nice to have a section on this in the tutorial though.

**Pull request merged**
