### PR TITLE
control over color/facetting for some plots

### PR DESCRIPTION
**Pull request by zmjones**
- plotThreshVsPerf
 - plotThreshVsPerfGGVIS
 - plotLearningCurve
 - plotLearningCurveGGVIS

smarter defaults
arguments for color/facet for ggplot
arguments for color/interaction for ggvis
added additional args to news

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks -- just out of curiosity, why did you comment the tests for the ggvis versions?

**Comment by zmjones** [comment]
I run them interactively but they all call Shiny, which you have to kill manually, so they don't seem to work with this sort of test. I am not sure if there is a better way to test them.

**Comment by larskotthoff** [comment]
Ok, this is something to think about for the future, but fine for now.

Another thing that I've noticed is that facet and colour are mutually exclusive and binary, so you could have just a single argument and infer the other from that. The advantage would be less code for argument checking. Would it make sense to only specify facet and infer colour from that? Again something to think about.

Merging the PR now.

**Comment by zmjones** [comment]
Yes that probably does make sense. I can just change that now. I also think I missed the case where the user sets both to the same thing, which this would also solve.

**Pull request merged**
