### PR TITLE
compute partial predictions for features w/o conditioning

### PR DESCRIPTION
**Pull request by zmjones**
- adds interaction flag to generatePartialPredictionData,
   when FALSE and length(features) > 1, partial predictions
   for each feature are computed
 - plotPartialPrediction and plotPartialPredictionGGVIS can
   use facetting/shiny to visualize the above type of output

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Could you update NEWS as well please?

**Comment by zmjones** [comment]
I didn't think it made sense to since this function wasn't in 2.4, so it will appear at the next CRAN release that it is just a new function with this feature.

**Comment by berndbischl** [comment]
yup, if a new function appears, only mention it under "new functions". We do not need to track changes before it ever went to cran. only in extreme case explain in the text above why this function was added. in most cases it should be inferrable from the function name. and people can simply read the doc file.

**Comment by larskotthoff** [comment]
Ok, thanks.

**Pull request merged**
