### PR TITLE
integrate class weights

### PR DESCRIPTION
**Pull request by kerschke**
hopefully, finally solving issue #123

### CODE REVIEW

**Comment by kerschke** [comment]
hmm.. any idea what travis is trying to tell me?

**Comment by larskotthoff** [comment]
Looks like a bug in checkmate. There was another commit to that repo a few minutes ago; I've restarted the build.

**Comment by kerschke** [comment]
Perfect. Michels fixing of checkmate and your restart of the PR resulted in a succesful built :-)

**Comment by mllg** [comment]
I will tell Travis to use the CRAN version of checkmate. Something like this should not happen ;)

**Comment by berndbischl** [comment]
Please update NEWS

**Comment by kerschke** [comment]
Ok, I just did. Sorry for forgetting about that.

**Comment by berndbischl** [comment]
Ok thx but you need to mention every new function. And if args in other functions have changed. You at least forgot the getter right?

**Comment by kerschke** [comment]
Arghh.. you're right.

**Comment by kerschke** [comment]
Better?

**Pull request merged**
