### PR TITLE
add ggvis functions

### PR DESCRIPTION
**Pull request by zmjones**
- plotROCRCurvesGGVIS
 - plotLearningCurveGGVIS
 - plotTuneMultiCritResultGGVIS
 - plotThresVsPerfGGVIS
 - plotFilterValuesGGVIS

added myself as a contributor
adds ggvis and shiny to imports
add tests for all new (and missing) plot methods

missing is plotLearningPrediction, which is one of my next tasks.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks, looks good to me.

I'm nitpicking here, but could you please keep the imports etc in alphabetical order?

**Comment by zmjones** [comment]
fixed now

**Comment by schiffner** [comment]
Thank you, looks very good to me, too.
Sorry for a little more nitpicking, just noticed while reading through the code:

generateLearningCurve.R:
l. 77: ggplot2
l. 110: missing word

generateROCRCurves.R
l. 266 should be: Default is \code{FALSE}

**Comment by zmjones** [comment]
those are fixed now. thanks! nitpicks are welcome!

**Pull request merged**
