### PR TITLE
add generateThreshVsPerfData

### PR DESCRIPTION
**Pull request by zmjones**
- methods for List of Prediction, ResampleResults, Prediction,
   ResampleResult, and BenchmarkResult
 - added facetting and interactivity in plotThreshVsPerf and
   plotThreshVsPerfGGVIS respectively
 - new tests

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks Zach. Could you also mention the facetting and that the methods support lists now in NEWS as well please?

**Comment by berndbischl** [comment]
I guess Lars is right here, but a short reminder: 
If a method is completely new for a current version, we do not need to doc its "development" in NEWS.
Just saying.

**Comment by zmjones** [comment]
Ok will do.

**Comment by larskotthoff** [comment]
I would mention the list support with the functions themselves and the facetting in a separate point.

**Comment by zmjones** [comment]
Ok, will fix that momentarily. I merged this branch with another I just issued a PR for. Sorry for the mess! All these changes are in the other PR and the commits are separate.

**Pull request closed without merging**
