### PR TITLE
Improvements in plotROCRCurves #247

### PR DESCRIPTION
**Pull request by luizfox**
- Defaults of avg to match obj
- Default of add.diag set to FALSE
- Added the ... argument to pass graph parameters
- ylim determined to match the list passed

### CODE REVIEW

**Comment by larskotthoff** [comment]
There are a few warnings when building the package (see the travis output). Please also remember to regenerate the documentation. The failed test does seem to be related to the changes that you've made.

You can run the tests yourself using the test_all.R script. We're using the standard devtools/testthat approach for testing, documenting etc. Let me know if you need any additional information.

**Comment by luizfox** [comment]
Hi Lars, 

thanks for the comments. After some new commits, I have seen the logs and I wasn't able to figure out the problem on trevis. Can  you please take a look? Do you have any ideas?

Thanks.

**Comment by larskotthoff** [comment]
It looks like the test failure is unrelated to your change -- you may have to pull in the changes from the master branch (rebase). However, there are still a few warnings related to `plotROCRCurves`, could you have a look at those please? You can test locally (those warnings come from `R CMD check`) before committing/pushing.

**Comment by luizfox** [comment]
Thanks again the tips, Lars.

I did the rebase/refork, and it looks like there's a problem on the base package. I tried to compile it without any changes, and it didn't work out.

`Last 13 lines of output:
  makeRegrTask(data = multiclass.df, target = multiclass.target) does not match
''numeric''. Actual value: "Error in test_check("mlr", filter = "base") : \n  As
sertion on 'Species' failed: Must be numeric\n"`

So I'm sending my changes anyway.

**Comment by larskotthoff** [comment]
Hmm, it seems to work fine in Travis -- could you do a clean checkout of the master branch and see if that works for you? Also, is your pull request related to this one? It looks to me like the commit there should be part of this pull request.

**Comment by luizfox** [comment]
I did a clean checkout, but I got the error I've reported. 
And yes, my pull request (#272) is related with this one, but since I've started a clean checkout, I decided to make a clean pull request as well.

**Comment by larskotthoff** [comment]
Hmm, the master branch is fine on travis (see https://travis-ci.org/berndbischl/mlr/builds/55603156), so it must be something you've introduced. In your new pull request you're fixing issues that are introduced by this one, so please merge the two -- the idea is that we can merge a single pull request into mlr that will give us the fix and not introduce new warnings/errors.

**Comment by mllg** [comment]
1. The error in the travis log regarding kohonen is not your fault (there were some upstream changes we did not yet adapted to)
2. Please familiarize yourself with roxygen2. It looks like you've changed the docs in the Rd file directly?
3. Please rebase many small commits into one.

**Comment by mllg** [comment]
> The error in the travis log regarding kohonen is not your fault (there were some upstream changes we did not yet adapted to)

I think Lars is right: It seems like we already fixed this and you did not pull/rebase the master branch?

**Comment by luizfox** [comment]
Thanks for the comments.

Yes, I was editing the Rd file directly. I didn't know it. I got used to it a little more now.

When I was trying to get catch the problem, I deleted my fork of the master branch and created a new one, and then I created another pull request, #272. May I close this one and rebase with the #272?

**Comment by larskotthoff** [comment]
Yes please, could you make a single pull request that has everything?

**Comment by luizfox** [comment]
#274 will deal with this pull request.

**Pull request closed without merging**
