### PR TITLE
Naming

### PR DESCRIPTION
**Pull request by zmjones**
I added a test for the custom measure case that broke the tutorial and expanded the original idea a little bit so that it is more consistent across all the plots.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Wait, this test won't actually break with the previous implementation that used `get()`, or am I missing something?

**Comment by zmjones** [comment]
No. I was just doing what @schiffner suggested in #367.

**Comment by larskotthoff** [comment]
Ok thanks, just checking.

**Comment by zmjones** [comment]
It would be good if we could regenerate the tutorial after this. Partially to be sure everything worked correctly, but also to have the better plot labels in there.

**Comment by larskotthoff** [comment]
Sure, I'll kick off another build after this is merged.

**Pull request merged**
