### PR TITLE
Ready to merge?

### PR DESCRIPTION
**Pull request by IcedragonP**

### CODE REVIEW

**Comment by berndbischl** [comment]
Is it possible to put the changes into a single commit so I can check the diff in an easier way?

**Comment by IcedragonP** [comment]
Maybe is it ok, if you watch this site?: 
https://github.com/berndbischl/mlr/compare/master...IcedragonP:master

**Comment by larskotthoff** [comment]
Could you also please have more descriptive commit messages in the future and ideally describe what was implemented in the pull request? Reading the commit logs and I wasn't able to deduce that you  implemented support for multi-label classification.

**Comment by berndbischl** [comment]
I am iterating over this completely now anyway and will merge on the CL.

**Comment by larskotthoff** [comment]
Is this still relevant or can it be closed?

**Comment by berndbischl** [comment]
I will close this, but @IcedragonP needs to take care of his local code that we have not merged and may or may not still be useful

**Pull request closed without merging**
