### PR TITLE
bugfixes for generatePartialPredictions

### PR DESCRIPTION
**Pull request by zmjones**
one is related to factor levels in `generateFeatureGrid` and the other the group aesthetic for probability plots in `plotPartialPrediction`.

I am working on making tests for plots and adding more error checking for the plotting functions (here specifically) as well. Neither are adequate now.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Is it possible to have a unit test for the bug you've fixed?

**Comment by zmjones** [comment]
Not for the plot (yet) but for the factor levels yes. I will amend this in a moment.

**Comment by berndbischl** [comment]
Will pull it in now, zach made a note for the unit test

**Comment by larskotthoff** [comment]
I would have at least waited until the travis build finished, but ok :)

**Comment by berndbischl** [comment]
Sorry, wanted to try it out :)

**Comment by berndbischl** [comment]
(will not do this often though, busy and also was talking to zach)

**Comment by zmjones** [comment]
I have a question about `generateFeatureGrid`. When an integer feature is passed I am not sure what to do. `seq.int` returns a numeric even if `length.out` is less than the range of `abs(from-to`. e.g, `is.integer(seq.int(1:3, length.out = 3))` is `FALSE`. If I am correct in thinking that since integers are also numerics (and are treated the same by all learning algorithms) then this won't be a problem. If you wanted you could subsample or bootstrap the observed values of the feature (an option to the function).

**Comment by zmjones** [comment]
I guess I could just do `fmin:fmax` and throw an error if that isn't equal to `cutoff` but that seems like a pain.

**Comment by berndbischl** [comment]
Ints are not treated always the same. I would be careful here. If it was an int before, it should be later.

**Comment by berndbischl** [comment]
I mean, there is a certain stepsize right for every feature? Cant you round this to the next reasobale value?

**Comment by berndbischl** [comment]
Or are we simply talking about the data type that seq.int returns?

**Comment by zmjones** [comment]
yes I suppose I could do that

**Comment by berndbischl** [comment]
But try to make sure that it stays an int, to be sure...

**Comment by zmjones** [comment]
I think I can just coerce the sequence to an `int` and that will be fine.

**Comment by zmjones** [comment]
actually `sort(rep(min:max, length.out = cutoff))` is probably the best. thanks for the help

**Pull request merged**
