### PR TITLE
sorting and n_show interactive in plotFilterValuesGGVIS

### PR DESCRIPTION
**Pull request by zmjones**
- sorting is now controlled with a radio button in the sidebar
 - number of features to show is controlled by numeric input
 - interactive flag removed
 - refactoring

### CODE REVIEW

**Comment by schiffner** [comment]
Thanks, that's very cool!
I will merge, just waiting for travis to finish.

**Comment by schiffner** [comment]
While playing around I just found a small problem with the `n.show` option: In the ggvis plot, when decreasing  `n.show`, the features vanish in the order they have in the data set (the last column is the first to go). I guess we want it consistent with `plotFilterValues`, i.e., remove the least important feature first.

Here is an extreme example, where the most important feature vanishes first:

```
getTaskFeatureNames(bh.task)
>  [1] "crim"    "zn"      "indus"   "chas"    "nox"     "rm"      "age"     "dis"     "rad"     "tax"     "ptratio" "b"      
> [13] "lstat"
fv = generateFilterValuesData(bh.task, method = "cforest.importance")
plotFilterValuesGGVIS(fv)
```

Could you please fix?

**Comment by zmjones** [comment]
ah, forgot that i wasn't sorting the data.frame anymore, just the factor levels. thanks! fix incoming

**Comment by schiffner** [comment]
Thx :)

**Pull request merged**
