### PR TITLE
including class weights (cf. issue #123)

### PR DESCRIPTION
**Pull request by kerschke**
Included the class weights property for classification learner and also added some man-files (which apparently were not committed so far).

### CODE REVIEW

**Comment by berndbischl** [comment]
For now it is OK, but pls dont add man add NAMESAPCE to the PR. this just makes it harder to merge I guess.

**Comment by berndbischl** [comment]
Don use \code\link for stuff like character. Pls fix

**Comment by berndbischl** [comment]
Also pls do NOT put unrelated stuff into one PR. You are also changing params in other learners and so on.

**Comment by berndbischl** [comment]
And the unit test you wrote belongs to group "base", not "classif". 
"classif" is (as one can really see) just a group for all indivdual classif learners. 
Please really look at this with open eyes, so I dont have to check all of this....

**Comment by berndbischl** [comment]
AND: getClassWeightsParams looks not good. 
- You are using assertion wrong
- Why do you return a named list of values? 
- Isnt the arg just a string and not a char vec?

**Comment by kerschke** [comment]
> And the unit test you wrote belongs to group "base", not "classif".
"classif" is (as one can really see) just a group for all indivdual classif learners. 

I thought about that, but (as you mentioned in previous conversations) *base* should contain only the minimum stuff, so I decided to put it into *classif*.

> Also pls do NOT put unrelated stuff into one PR. You are also changing params in other learners and so on. 

In that case, it would be great if everybody could run all checks and all builds before committing. Otherwise, I'll always have to check in each commit which files I need to ignore (again)..

> Don use \code\link for stuff like character. Pls fix

Why not? I mean, I definitely can change it, but do not see the point.

> AND: getClassWeightsParams looks not good. 
> - You are using assertion wrong

Could you actually be more precise? What am I doing wrong / how should I use it instead?

> - Why do you return a named list of values? 

Because I thought it's useful to have the entire information of the class weight parameter of the learner - not just the ID. If you prefer the latter, I could do that instead..

> - Isnt the arg just a string and not a char vec?

Actually you're right. I forgot that there exists `assertString` as well.

**Comment by berndbischl** [comment]
> base should contain only the minimum stuff,

No, base should contain as MUCH as possible, if it creates no problems on CRAN. Eg timing problems. 
If you can create a FAST test, put in in base. Stuff only goes into other groups if it is a big loop over like all filters or does something technically annoying like parallel stuff. check the basic API in base

**Comment by berndbischl** [comment]
> Don use \code\link for stuff like character. Pls fix Why not? I 

Because I say so (= it is consistent with the rest of package)

**Comment by berndbischl** [comment]
> You are using assertion wrong

You cannot put an arbitrary logical clause into assert

**Comment by berndbischl** [comment]
Lets try to talk about the rest in 20 mins, some stuff I dont get

**Comment by kerschke** [comment]
Alright.

**Pull request closed without merging**
