### PR TITLE
plotROCRCurves with ggplot2

### PR DESCRIPTION
**Pull request by zmjones**
- use `ROCR::performance` but not `ROCR::plot`
 - handle averaging in mlr rather than `ROCR::plot`
- `ggplot2` instead of base graphics
 - test for basic input to all methods

Also I removed the global assignment I mentioned to Lars/Julia.

### CODE REVIEW

**Comment by zmjones** [comment]
the build error appears unrelated but i am not sure.

**Comment by larskotthoff** [comment]
Ok, the master mlr build succeeds, but I can't tell the difference between them because travis cuts the output at 10000 lines. I'm not sure what the best way to proceed is there -- it may be beneficial for you to create a new travis job that uses your copy of the repository (also so you can test without creating pull requests) and runs only the relevant subset of the tests, but IIRC travis doesn't make running a subset of the tests easy unfortunately.

**Comment by larskotthoff** [comment]
I ran the test locally and it worked fine. I'll merge this for now, we can always revert later.

**Comment by schiffner** [comment]
Sorry for not commenting earlier, was visiting relatives and had to drive home first. I just saw we have now two files with nearly identical tests that should be merged:
https://github.com/berndbischl/mlr/blob/master/tests/testthat/test_base_rocr.R and
https://github.com/berndbischl/mlr/blob/master/tests/testthat/test_base_plotROCRCurves.R

**Comment by zmjones** [comment]
ah ok, just did a poor job searching for existing tests. thanks!

**Comment by schiffner** [comment]
Not a problem, I am merging the files now. (And this way, I just found a typo in the old tests that I missed before. So thank you :) )

**Comment by zmjones** [comment]
[here](https://api.travis-ci.org/jobs/64010699/log.txt?deansi=true) is the full log. 

there is this

```
Client failed to connect to the D-BUS daemon:
  Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
  GConf Error: No D-BUS daemon running
```

and then this

```
R: malloc.c:3795: _int_malloc: Assertion `victim->fd_nextsize->bk_nextsize == victim' failed.
```

and then check fails. i thought maybe this was my fault since the test was outputting to the display device  but this was when i was under the impression that there was no older test for `plotROCRCurves`.

**Comment by larskotthoff** [comment]
Ah, useful to know that you can get the full output!

The error seems to be unrelated to your changes though, apparently it's caused by `tests/run-classif.R`.

**Pull request merged**
