### PR TITLE
multiple filter methods for plot/getFilterValues

### PR DESCRIPTION
**Pull request by zmjones**
- getFilterValues can now take a vector of methods
 - plotFilterValues can use facetting
 - plotFilterValuesGGVIS can use a Shiny app to interactively
   show different filter methods
 - minor modifications to class 'FilterValues'
 - minor modifications to function 'FilterFeatures'

This passed the feature selection tests and check. I can't write tests for the Shiny app though.

### CODE REVIEW

**Comment by zmjones** [comment]
So I implemented the latter suggestion. Now in `filterFeatures` the default method is `NULL`. If `fval` is passed and the `data` element has length 1 then I just extract the name of this element (i.e. that becomes the default method`. If there are multiple filters in `fval` then the user has to set one as `method` which is then extracted. I avoided the side effect of not having a default filter when calling `filterFeatures` by substituting the default filter (by removing the method argument) when no `fval` is passed and `method` is still `NULL`. I am not sure I documented it correctly though.

**Comment by zmjones** [comment]
I talked with Bernd a bit and am now working on returning a `data.frame` instead of a named list from `getFilterValues`.

**Comment by larskotthoff** [comment]
Ok, could you also please check the default behaviour (i.e. no method selected explicitly)? It looks to me like you'd get an error message at the moment, which is different to the behaviour before.

**Comment by zmjones** [comment]
ok i will check that again.

**Pull request closed without merging**
