### PR TITLE
fix for "get" trouble

### PR DESCRIPTION
**Pull request by zmjones**
- getThreshVsPerfData now returns measure objects
 - simplifies name/id replacement code in learningcurve and threshvsperf
   plot functions

### CODE REVIEW

**Comment by schiffner** [comment]
Looks good to me. Thanks!
@berndbischl : Do you want to check, too?

**Comment by zmjones** [comment]
Yea that is right. I wasn't aware of mapValues. I can use that though. Will change momentarily.

**Comment by berndbischl** [comment]
Actually we wrote that for when we use ggplot. You so often want to "rename" stuff for plots.

**Comment by zmjones** [comment]
Ah ok.

**Comment by zmjones** [comment]
mapValues is in use now. that is a nice solution

**Comment by larskotthoff** [comment]
Could you add a unit test that fails with the old code please?

**Comment by zmjones** [comment]
I don't know how it fails. Bernd said that he didn't really either.

**Comment by schiffner** [comment]
Yes. I didn't manage to reproduce the error when running the code interactively. It only failed when building the tutorial (on my computer and on Travis).

What we could do is to replace one of the mlr built-in measures in the tests for e.g. plotThreshVsPerf, plotLearningCurve and others by a user-defined one. This wouldn't have helped with the get-issue today, but might be useful in the future.

**Comment by larskotthoff** [comment]
Hrm, it seems to be very specific to knitr -- no idea what exactly is going on. Merging with the hope that I don't break everything again :)

**Comment by zmjones** [comment]
Ok, I'll issue a new PR for the test.

**Pull request merged**
