### PR TITLE
fixes #247 plotROCRCurves

### LINKED ISSUE #247: Improvements in plotROCRCurves
Some things I noticed when writing the tutorial. 

  * Defaults:
  
    1. The default is `avg = "threshold"`. That does not make much sense if `obj` is a (`list` of)
       `Prediction` objects. The default should depend on `obj`. In my opinion we should set `avg = "none"` for (`list`s of) `Prediction` objects and `avg = "threshold"` for (`list`s of) `ResamplePrediction` objects and `BenchmarkResult`s.

    2. The colored boxes in the legend are not needed. Therefore keep `fill = NULL` (the default in
       `legend`).

    3. The default is `add.diag = TRUE`: The diagonal does only make sense for ROC curves
       and it's tedious to set is to `FALSE` when plotting other performance measures.
       Maybe the default should be `FALSE` or depend on `meas1` and `meas2`.

  * At the moment standard `plot` arguments like `xlab` or `ylim` cannot be used.
    Many graphical options of ROCR's `plot` function also do not work.
    Either give `plotROCRCurves` a `...` argument or something like `plot.args` to pass
    graphical parameters.

  * Determine `ylim` internally to prevent the following:

    ```
    lrn1 = makeLearner("classif.lda", predict.type = "prob")
    mod1 = train(lrn1, sonar.task)
    pred1 = predict(mod1, task = sonar.task)
    
    lrn2 = makeLearner("classif.ksvm", predict.type = "prob")
    mod2 = train(lrn2, sonar.task)
    pred2 = predict(mod2, task = sonar.task)

    plotROCRCurves(list(lda = pred1, ksvm = pred2), meas1 = "acc", meas2 = "cutoff", avg = "none",
      add.diag = FALSE, legend.args = list(x = "bottom"))
    ````

### PR DESCRIPTION
**Pull request by zmjones**
- can pass arguments to plot via plot.args
 - ylim is set by finding the range of the y.values slot of elements of the list rocr.perfs across all elements
 - add.diag is now NULL by default
   + set to FALSE unless meas1 = "tpr" and meas2 = "fpr", appropriate
 - assertions were added in the generic method
 - fill = FALSE and bty = "n"
 - news updated
 - docs updated

cleaned version of previous PR #259

### CODE REVIEW

**Comment by zmjones** [comment]
should I rebase this and fix the merge conflicts myself?

**Comment by berndbischl** [comment]
would be thankful for any dilligent fixing, i am traveling

**Comment by zmjones** [comment]
ok, should be good to go now, it was just a conflict with NEWS.

**Comment by zmjones** [comment]
I was wondering what, if anything to do with failed tests due to things other than the code I am working on. I see that `predict.kohonen’ is no longer being exported and the associated error in `predict_classif_xyz.R` and I get a note about the `thirdparty` directory. Is there a reason (or a discussion I can read) about why `predict.kohonen` is referenced explicitly?

**Pull request closed without merging**
