### PR TITLE
introduce tunable-flag

### PR DESCRIPTION
**Pull request by kerschke**
iterated over the parameters of the integrated learners and eventually defined tunable = FALSE (as the default is tunable = TRUE)

### CODE REVIEW

**Comment by berndbischl** [comment]
I sometimes see "tunable = TRUE"
This looks like a bug. Please dont merge without PROPERLY checking.

**Comment by jakob-r** [comment]
I have to admit I oversaw these three instances
@kerschke any specific reason?

**Comment by berndbischl** [comment]
They look like typos, as the params seem to be stuff like "verbose".

And usually we want to rely on the default TRUE. And not note it explicitly.

**Comment by kerschke** [comment]
You're right. They were just typos and I've fixed them.
Sorry for that..

**Pull request merged**
